name: http_debugger
description: "Global HTTP interceptor via HttpOverrides to proxy all traffic through local network debugger."
version: 0.2.2
repository: https://github.com/cherrypick-agency/flutter_network_debugger
homepage: https://github.com/cherrypick-agency/flutter_network_debugger
issue_tracker: https://github.com/cherrypick-agency/flutter_network_debugger/issues
topics:
  - http
  - debug
  - proxy
  - overrides

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

