name: http_debugger
description: "Глобальный перехватчик HTTP через HttpOverrides для проксирования всего трафика через локальный network debugger."
version: 0.1.0
repository: https://github.com/cherrypick-agency/flutter_network_debugger
homepage: https://github.com/cherrypick-agency/flutter_network_debugger
issue_tracker: https://github.com/cherrypick-agency/flutter_network_debugger/issues
topics:
  - http
  - debug
  - proxy
  - overrides

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0


