name: web_socket_channel_debugger
description: "Helper to attach network-debugger proxy to package:web_socket_channel (reverse/forward)."
version: 0.2.1
repository: https://github.com/cherrypick-agency/flutter_network_debugger
homepage: https://github.com/cherrypick-agency/flutter_network_debugger
issue_tracker: https://github.com/cherrypick-agency/flutter_network_debugger/issues
topics:
  - websocket
  - web-socket
  - debug
  - proxy
  - reverse

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  web_socket_channel: ^3.0.3

dev_dependencies:
  test: ^1.25.0
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0

