version: "3.9"
services:
  wsproxy:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
      - LOG_LEVEL=info
      - INSECURE_TLS=1


