version: "3.9"
services:
  network-debugger:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "9092:9092"  # UI
      - "9091:9091"  # Forward proxy
    environment:
      - ADDR=:8080
      - LOG_LEVEL=info
      - INSECURE_TLS=1
