version: "3.9"
services:
  network-debugger:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "9091:9091"
    environment:
      - ADDR=:8080
      - LOG_LEVEL=info
      - INSECURE_TLS=1
