name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Setup Flutter (for web ui)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Flutter pub get
        working-directory: frontend
        run: flutter pub get

      - name: Build artifacts
        run: |
          make package
          # Build Flutter web (hash routing by default works with index.html)
          cd frontend && flutter build web --release

      - name: Upload artifacts (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: web/downloads/**

      - name: Upload web (for pages)
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: frontend/build/web/**

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: downloads
          path: web/downloads

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            web/downloads/**
          body: |
            Downloads page: https://<my-pages-domain>/download.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: webapp

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webapp

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

